# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'HyuJokbo' do
	#Firebase
	pod 'Firebase/Core'
	pod 'Firebase/Database'
  pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	
	#Facebook
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'
	
	#Google
	pod 'GoogleSignIn'

  #BSImagePicker
  pod "BSImagePicker", "~> 2.4"
end
